name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Оновлено до v4, яка використовує Node.js 20
    - name: Set up Node.js
      uses: actions/setup-node@v4 # Оновлено до v4, яка використовує Node.js 20
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Check for package.json
      run: ls -la diploma && cat diploma/package.json
    - name: Install dependencies
      run: cd diploma && npm install
    - name: Run build
      run: cd diploma && npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Оновлено до v4, яка використовує Node.js 20
    - name: Set up Node.js
      uses: actions/setup-node@v4 # Оновлено до v4, яка використовує Node.js 20
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Check for package.json
      run: ls -la diploma && cat diploma/package.json
    - name: Install dependencies
      run: cd diploma && npm install
    - name: Run tests
      run: cd diploma && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Оновлено до v4, яка використовує Node.js 20
    - name: Set up Node.js
      uses: actions/setup-node@v4 # Оновлено до v4, яка використовує Node.js 20
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Check for package.json
      run: ls -la diploma && cat diploma/package.json
    - name: Install dependencies
      run: cd diploma && npm install
    - name: Deploy to AWS
      run: |
        set -euxo pipefail
        cd diploma
        ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
