name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Display current directory
      run: pwd
    - name: Display root directory structure
      run: ls -Rla /
    - name: Display workspace directory structure
      run: ls -Rla ${{ github.workspace }}
    - name: Find package.json in workspace
      run: find ${{ github.workspace }} -name "package.json"
    - name: Install dependencies
      run: cd <path-to-directory> && npm install
    - name: Run build
      run: cd <path-to-directory> && npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Install dependencies
      run: cd <path-to-directory> && npm install
    - name: Run tests
      run: cd <path-to-directory> && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Display Node.js version
      run: node -v
    - name: Display npm version
      run: npm -v
    - name: Install dependencies
      run: cd <path-to-directory> && npm install
    - name: Deploy to AWS
      run: |
        set -euxo pipefail
        cd <path-to-directory>
        ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
